# ===================================
# Configuration
# ===================================

spring:

  application:
    name: creditcard-processor

  h2:
    console:
      enabled: true
      path: /h2


  datasource:
    url: jdbc:h2:file:~/creditcard-processor
    username: sa
    password:

  flyway:
    clean-on-validation-error: true

server:
  port: 9090

spring-doc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html

# ===================================
# application properties
# ===================================

application:
  logging:
    logger: CONSOLE
  swagger:
    enabled: true




